### ISSUE TITLE
NNInputSystem : 게임에 포커스 아닐때도 키 입력 되는 현상

### ISSUE THREAD

**Issue by namse** [kciter/NNGameFramework#33]
알트탭 누르고 메신저를 한다던가, 공략 검색을 할 때 등등, 포커스가 게임인 상황 아닌 상태에서도 키 입력이 다 받아지고 있습니다.

현재 게임에 대한 포커스가 아니면 키 입력을 못받게 하는게 어떨까요?

**Comment by kciter** [comment]
ㅇㅋ
