### ISSUE TITLE
m_ZIndex 값 적용 관련 이슈

### ISSUE THREAD

**Issue by quxn6** [kciter/NNGameFramework#8]
상위 object가 자식들에게 지정해준 ZIndex값이 자식의 자식이 갖는 ZIndex보다 우선함

때문에 자식의 자식이 갖는 ZIndex가 무시됨

→ 자식의 자식은 ZIndex가 0이어도 그 부모의 ZIndex가 다른 자식들보다 높을 경우 더 상위에 표시된다.

**Comment by kciter** [comment]
해결
