### ISSUE TITLE
SetVisible 관련 이슈

### ISSUE THREAD

**Issue by quxn6** [kciter/NNGameFramework#9]
생성자에서 Setvisible을 하면 잘 먹음

이후에 다른 함수에서 Setvisible을 false하면 디버그로 확인했을때, 값이 false여서 render에서 바로 return됨에도 불구하고 계속 남아있음.

생성자에서 false한 것을 외부에서 true할 때도 마찬가지 인 것 같음

**Comment by kciter** [comment]
월요일날 다시한번 얘기해봐요
